//текущий просматриваемый ингридиент
export const SET_CURRENT_INGRIDIENT: 'SET_CURRENT_INGRIDIENT' = "SET_CURRENT_INGRIDIENT";
export const RESET_CURRENT_INGRIDIENT: 'RESET_CURRENT_INGRIDIENT' = "RESET_CURRENT_INGRIDIENT";