//заказ
export const GET_ORDER_INFO: 'GET_ORDER_INFO' = "GET_ORDER_INFO";
export const GET_ORDER_INFO_FAILED: 'GET_ORDER_INFO_FAILED' = "GET_ORDER_INFO_FAILED";
export const GET_ORDER_INFO_SUCCESS: 'GET_ORDER_INFO_SUCCESS' = "GET_ORDER_INFO_SUCCESS";
