//регистрация
export const REGISTER_USER: 'REGISTER_USER' = "REGISTER_USER";
export const REGISTER_USER_FAILED: 'REGISTER_USER_FAILED' = "REGISTER_USER_FAILED";
export const REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS' = "REGISTER_USER_SUCCESS";

//авторизация
export const LOGIN_USER: 'LOGIN_USER' = "LOGIN_USER";
export const LOGIN_USER_FAILED: 'LOGIN_USER_FAILED' = "LOGIN_USER_FAILED";
export const LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS' = "LOGIN_USER_SUCCESS";

//восстановление пароля
export const PASSWORD_RECOVER: 'PASSWORD_RECOVER' = "PASSWORD_RECOVER";
export const PASSWORD_RECOVER_FAILED: 'PASSWORD_RECOVER_FAILED' = "PASSWORD_RECOVER_FAILED";
export const PASSWORD_RECOVER_SUCCESS: 'PASSWORD_RECOVER_SUCCESS' = "PASSWORD_RECOVER_SUCCESS";

//сброс пароля
export const PASSWORD_RESET: 'PASSWORD_RESET' = "PASSWORD_RESET";
export const PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED' = "PASSWORD_RESET_FAILED";
export const PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS' = "PASSWORD_RESET_SUCCESS";

//запрос данных пользователя
export const GET_USER: 'GET_USER' = "GET_USER";
export const GET_USER_FAILED: 'GET_USER_FAILED' = "GET_USER_FAILED";
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = "GET_USER_SUCCESS";

//обновление данных пользователя
export const UPDATE_USER: 'UPDATE_USER' = "UPDATE_USER";
export const UPDATE_USER_FAILED: 'UPDATE_USER_FAILED' = "UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = "UPDATE_USER_SUCCESS";

//выход из системы
export const LOGOUT_USER: 'LOGOUT_USER' = "LOGOUT_USER";
export const LOGOUT_USER_FAILED: 'LOGOUT_USER_FAILED' = "LOGOUT_USER_FAILED";
export const LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS' = "LOGOUT_USER_SUCCESS";

